### ISSUE TITLE
git stages deletes of all files and untracks all files when starting new story.

### ISSUE THREAD

**Issue by ChrisCPO** [daisybill/github_workflow#3]
Possible issue with git v2.24.0
When on master and I edit an existing file
Then I start my story `gw start -i xxxx`

expected:
stash create and checkout branch stash pop.

actual:
creates and checks out new branch but also
git stages all filesas deleted but also untracks all file and folders.

**Comment by BrianBorge** [comment]
Well then, [Re: [BUG] git stash pop --quiet deletes files in git 2.24.0
](https://www.spinics.net/lists/git/msg369540.html)

@benliscio noticed it in [an update to overcommit](https://github.com/sds/overcommit/commit/648383ff3cd9d51ab83de87f2bf64fa9a0d6d559
)



> Remove --quiet flag when popping stash
This was causing the entire repository to be deleted in situations where
there were no staged changes. It is a bug with the `--quiet` flag
itself: https://www.spinics.net/lists/git/msg369540.html
